name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MThemeAWSEC2: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ env.MThemeAWSEC2 }}

    - name: Deploy to EC2
      run: ssh -o StrictHostKeyChecking=no user@${{ env.EC2_IP }} "echo 'Deployment successful'"