name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Git Pull with rebase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd MThemeWeb/MThemeBackend
            git fetch origin
            git pull --rebase
            if [ $? -ne 0 ]; then
              git status
              # Manually resolve merge conflicts
              # git add <resolved_files>
              # git rebase --continue
              # git push
              exit 1
            fi